{
    package GCLang::EN::GCExport::GCExportHTML;

    use utf8;
###################################################
#
#  Copyright 2005-2010 Christian Jodar
#
#  This file is part of GCstar.
#
#  GCstar is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  GCstar is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with GCstar; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
#
###################################################
    
    use strict;
    use base 'Exporter';

    our @EXPORT = qw(%lang);

    our %lang = (
        'ModelNotFound' => 'Invalid template file',
        'UseFile' => 'Use file specified below',
        'WithJS' => 'Use Javascript',
       	'FileTemplate' => 'Template',
        'Preview' => 'Preview',
        'NoPreview' => 'No preview available',
        'TemplateExternalFile' => 'Template file',
        'Title' => 'Page title',
        'InfoFile' => 'Movies list is in file: ',
        'InfoDir' => 'Images are in: ',
        'HeightImg' => 'Height (in pixels) of the image to be exported',
        'OpenFileInBrowser' => 'Open generated file in web browser',
        'Note' => 'List generated by <a href="http://www.gcstar.org/">GCstar</a>',
        'InputTitle' => 'Enter search text',
        'SearchType1' => 'Title only',
        'SearchType2' => 'Full information',
        'SearchButton' => 'Search',    
        'SearchTitle' => 'Display only movies matching previous criteria',
        'AllButton' => 'All',
        'AllTitle' => 'Display all movies',
        'Expand' => 'Expand all',
        'ExpandTitle' => 'Display all movies information',
        'Collapse' => 'Collapse all',
        'CollapseTitle' => 'Collapse all movies information',
        'Borrowed' => 'Borrowed by: ',
        'NotBorrowed' => 'Available',
        'Top' => 'Top',
        'Bottom' => 'Bottom',
     );
}

1;
